# Generated by Django 6.0.1 on 2026-02-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
