# Generated by Django 6.0.1 on 2026-02-03 02:03

from django.db import migrations, models


def normalize_roles(apps, schema_editor):
    CompanyMembership = apps.get_model('tenancy', 'CompanyMembership')
    CompanyMembership.objects.filter(role='owner').update(role='OWNER')
    CompanyMembership.objects.filter(role='member').update(role='MEMBER')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_companymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='role',
            field=models.CharField(choices=[('ADMIN_EMPRESA', 'Admin Empresa'), ('GESTOR', 'Gestor'), ('RH', 'RH'), ('COLABORADOR', 'Colaborador'), ('OWNER', 'Owner'), ('MEMBER', 'Member')], default='COLABORADOR', max_length=30),
        ),
        migrations.RunPython(normalize_roles, reverse_code=noop),
    ]
