# Generated by Django 6.0.1 on 2026-02-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_company_legal_representative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assessment_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='cnae',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='risk_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='unit_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
