# Generated by Django 6.0.1 on 2026-02-11 00:40

import apps.tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_company_assessment_type_company_cnae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.tenancy.models.company_logo_upload_to),
        ),
    ]
