# Generated by Django 6.0.1 on 2026-02-18 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_alter_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consultancies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='consultancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='tenancy.consultancy'),
        ),
        migrations.CreateModel(
            name='ConsultancyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.consultancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultancy_memberships',
                'constraints': [models.UniqueConstraint(fields=('user', 'consultancy'), name='tenancy_membership_unique_user_consultancy'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='tenancy_membership_single_default_consultancy')],
            },
        ),
    ]
