# Generated by Django 6.0.1 on 2026-02-18 20:03

import apps.tenancy.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0015_consultancy_company_consultancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter 14 digitos numericos.', regex='^\\d{14}$')]),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.tenancy.models.consultancy_logo_upload_to),
        ),
    ]
