# Generated by Django 6.0.1 on 2026-02-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0016_consultancy_cnpj_consultancy_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
