# Generated by Django 6.0.1 on 2026-02-03 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenancy', '0002_alter_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('behavior', 'Comportamento'), ('safety', 'Seguranca'), ('workload', 'Carga de trabalho'), ('other', 'Outros')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], max_length=20)),
                ('channel', models.CharField(default='totem', max_length=60)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('is_anonymous', models.BooleanField(default=True, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-record_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('sentiment', models.CharField(choices=[('very_bad', 'Muito ruim'), ('bad', 'Ruim'), ('neutral', 'Neutro'), ('good', 'Bom'), ('very_good', 'Muito bom')], max_length=20)),
                ('mood_score', models.PositiveSmallIntegerField()),
                ('channel', models.CharField(default='totem', max_length=60)),
                ('is_anonymous', models.BooleanField(default=True, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'mood_records',
                'ordering': ['-record_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('report_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('custom', 'Personalizado')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Em fila'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='queued', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-record_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'risk_indicators',
                'ordering': ['-record_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('alert_type', models.CharField(choices=[('risk', 'Risco'), ('complaint', 'Queixa'), ('operational', 'Operacional')], max_length=20)),
                ('level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('acknowledged', 'Reconhecido'), ('closed', 'Fechado')], default='open', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.complaint')),
                ('risk_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.riskindicator')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-record_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['full_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('action_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Em andamento'), ('done', 'Concluida'), ('canceled', 'Cancelada')], default='planned', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to='core.complaint')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_support_actions', to='core.user')),
            ],
            options={
                'db_table': 'support_actions',
                'ordering': ['-record_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='core_complaint_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('occurrence_count__gte', 1)), name='core_complaints_occurrence_count_min'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('is_anonymous', True)), name='core_complaints_anonymous_only'),
        ),
        migrations.AddConstraint(
            model_name='moodrecord',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='core_moodrecord_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='moodrecord',
            constraint=models.CheckConstraint(condition=models.Q(('mood_score__gte', 1), ('mood_score__lte', 5)), name='core_mood_records_score_range'),
        ),
        migrations.AddConstraint(
            model_name='moodrecord',
            constraint=models.CheckConstraint(condition=models.Q(('is_anonymous', True)), name='core_mood_records_anonymous_only'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='core_report_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='riskindicator',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='core_riskindicator_period_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='riskindicator',
            unique_together={('company', 'code', 'record_date')},
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='core_alert_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='core_user_period_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('company', 'email'), ('company', 'username')},
        ),
        migrations.AddConstraint(
            model_name='supportaction',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='core_supportaction_period_valid'),
        ),
    ]
