# Generated by Django 6.0.1 on 2026-02-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_moodrecord_report_riskindicator_alert_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('assedio_moral', 'Assedio moral'), ('assedio_sexual', 'Assedio sexual'), ('discriminacao', 'Discriminacao'), ('conduta_antietica', 'Conduta antietica'), ('violencia_psicologica', 'Violencia psicologica'), ('other', 'Outros'), ('behavior', 'Comportamento'), ('workload', 'Carga de trabalho')], max_length=40),
        ),
    ]
