# Generated by Django 6.0.1 on 2026-02-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_details_alter_complaint_category'),
        ('tenancy', '0004_alter_companymembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'totems',
                'ordering': ['name'],
                'unique_together': {('company', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='totem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.totem'),
        ),
        migrations.AddField(
            model_name='moodrecord',
            name='totem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_records', to='core.totem'),
        ),
    ]
