# Generated by Django 5.2.4 on 2026-02-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_totem_complaint_totem_moodrecord_totem'),
        ('tenancy', '0004_alter_companymembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester_name', models.CharField(max_length=150)),
                ('department_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em atendimento'), ('RESOLVED', 'Concluido')], default='OPEN', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
                ('totem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to='core.totem')),
            ],
            options={
                'db_table': 'help_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
