# Generated by Django 5.2.4 on 2026-02-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_records', to='core.department'),
        ),
    ]
