# Generated by Django 5.2.4 on 2026-02-03 12:10

import django.db.models.deletion
from django.db import migrations, models


def seed_default_totem_options(apps, schema_editor):
    Company = apps.get_model('tenancy', 'Company')
    MoodType = apps.get_model('core', 'MoodType')
    ComplaintType = apps.get_model('core', 'ComplaintType')

    default_mood_types = [
        ('Muito bem', 'very_good', 5),
        ('Bem', 'good', 4),
        ('Mais ou menos', 'neutral', 3),
        ('Normal', 'neutral', 3),
        ('Triste', 'bad', 2),
        ('Irritado', 'very_bad', 1),
        ('Sobrecarregado', 'bad', 2),
        ('Cansado', 'bad', 2),
        ('Desmotivado', 'bad', 2),
        ('Desapontado', 'bad', 2),
        ('Estressado', 'very_bad', 1),
    ]
    default_complaint_types = [
        'Assedio moral',
        'Assedio sexual',
        'Discriminacao',
        'Conduta antietica',
        'Violencia psicologica',
        'Outro',
    ]

    for company in Company.objects.all():
        for label, sentiment, score in default_mood_types:
            MoodType.objects.get_or_create(
                company_id=company.id,
                label=label,
                defaults={
                    'sentiment': sentiment,
                    'mood_score': score,
                    'is_active': True,
                },
            )
        for label in default_complaint_types:
            ComplaintType.objects.get_or_create(
                company_id=company.id,
                label=label,
                defaults={
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_moodrecord_department'),
        ('tenancy', '0004_alter_companymembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'complaint_types',
                'ordering': ['label'],
                'unique_together': {('company', 'label')},
            },
        ),
        migrations.CreateModel(
            name='MoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('sentiment', models.CharField(max_length=20)),
                ('mood_score', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'mood_types',
                'ordering': ['label'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mood_score__gte', 1), ('mood_score__lte', 5)), name='core_mood_types_score_range')],
                'unique_together': {('company', 'label')},
            },
        ),
        migrations.RunPython(seed_default_totem_options, migrations.RunPython.noop),
    ]
