# Generated by Django 5.2.4 on 2026-02-03 12:54

import django.db.models.deletion
from django.db import migrations, models


def seed_alert_settings(apps, schema_editor):
    Company = apps.get_model('tenancy', 'Company')
    AlertSetting = apps.get_model('core', 'AlertSetting')
    for company in Company.objects.filter(is_active=True):
        AlertSetting.objects.get_or_create(
            company=company,
            defaults={
                'auto_alerts_enabled': True,
                'analysis_window_days': 30,
                'max_critical_complaints': 5,
                'max_negative_mood_percent': 35,
                'max_open_help_requests': 10,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_drop_legacy_key_columns'),
        ('tenancy', '0004_alter_companymembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'alert_recipients',
                'ordering': ['email'],
                'unique_together': {('company', 'email')},
            },
        ),
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_alerts_enabled', models.BooleanField(default=True)),
                ('analysis_window_days', models.PositiveSmallIntegerField(default=30)),
                ('max_critical_complaints', models.PositiveIntegerField(default=5)),
                ('max_negative_mood_percent', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('max_open_help_requests', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'alert_settings',
                'constraints': [models.UniqueConstraint(fields=('company',), name='core_alert_settings_one_per_company')],
            },
        ),
        migrations.RunPython(seed_alert_settings, migrations.RunPython.noop),
    ]
