# Generated by Django 5.2.4 on 2026-02-03 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alertrecipient_alertsetting'),
        ('tenancy', '0004_alter_companymembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(choices=[('RECEIVED', 'Recebido'), ('INVESTIGATING', 'Em apuracao'), ('CLOSED', 'Encerrado')], default='RECEIVED', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplaintActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint_status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('INVESTIGATING', 'Em apuracao'), ('CLOSED', 'Encerrado')], max_length=20)),
                ('action_note', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_histories', to='core.complaint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_action_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint_action_histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
