# Generated by Django 5.2.4 on 2026-02-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_complaint_complaint_status_complaintactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='severity',
        ),
    ]
