# Generated by Django 5.2.4 on 2026-02-03 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_complaint_severity'),
        ('tenancy', '0004_alter_companymembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequestActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em atendimento'), ('RESOLVED', 'Concluido')], max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_request_action_histories', to=settings.AUTH_USER_MODEL)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_histories', to='core.helprequest')),
            ],
            options={
                'db_table': 'help_request_action_histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
