# Generated by Django 6.0.1 on 2026-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_helprequestactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(choices=[('RECEIVED', 'Recebido'), ('INVESTIGATING', 'Em apuração'), ('CLOSED', 'Encerrado')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintactionhistory',
            name='complaint_status',
            field=models.CharField(choices=[('RECEIVED', 'Recebido'), ('INVESTIGATING', 'Em apuração'), ('CLOSED', 'Encerrado')], max_length=20),
        ),
    ]
