# Generated by Django 5.2.4 on 2026-02-06 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_report_ai_content_fields'),
        ('tenancy', '0005_company_address_city_company_address_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'ghes',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
