# Generated by Django 5.2.4 on 2026-02-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ghe'),
        ('tenancy', '0005_company_address_city_company_address_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planejada'), ('ACTIVE', 'Ativa'), ('PAUSED', 'Pausada'), ('FINISHED', 'Encerrada')], default='PLANNED', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='core_campaigns_period_valid')],
            },
        ),
    ]
