# Generated by Django 5.2.4 on 2026-02-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_campaign_response'),
        ('tenancy', '0005_company_address_city_company_address_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignresponse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company'),
        ),
    ]
