# Generated by Django 5.2.4 on 2026-02-07 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_campaign_report_settings_attachments'),
        ('tenancy', '0011_company_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignreportaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company'),
        ),
        migrations.AlterField(
            model_name='campaignreportsettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company'),
        ),
    ]
