# Generated by Django 6.0.1 on 2026-02-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_campaignreportaction_company_and_more'),
        ('core', '0027_department_ghe'),
    ]

    operations = [
    ]
