# Generated by Django 6.0.1 on 2026-02-10 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_drop_company_id_technical_responsible'),
        ('tenancy', '0013_company_assessment_type_company_cnae_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.company')),
                ('departments', models.ManyToManyField(blank=True, related_name='job_functions', to='core.department')),
                ('ghes', models.ManyToManyField(blank=True, related_name='job_functions', to='core.ghe')),
            ],
            options={
                'db_table': 'job_functions',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
