# Generated by Django 6.0.1 on 2026-02-11 00:00

from decimal import Decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_jobfunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.PositiveSmallIntegerField()),
                ('question_number', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('actions', models.JSONField(blank=True, default=list)),
                ('trigger_score_lt', models.DecimalField(decimal_places=2, default=Decimal('4.30'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='core_standardactionplan_set', to='tenancy.company')),
            ],
            options={
                'db_table': 'standard_action_plans',
                'ordering': ['step', 'question_number'],
                'unique_together': {('company', 'question_number')},
            },
        ),
    ]
