# Generated by Django 6.0.1 on 2026-02-11 00:00

from decimal import Decimal
from django.db import migrations


ACTION_PLAN_DATA = [
    {
        'step': 2,
        'question_number': 1,
        'question_text': 'Diferentes áreas exigem coisas difíceis de conciliar?',
        'actions': [
            'Mapear conflitos de demandas e definir prioridades formais entre setores.',
            'Estabelecer canal de alinhamento intersetorial semanal.',
            'Formalizar fluxo único de solicitação de tarefas.',
        ],
    },
    {
        'step': 2,
        'question_number': 2,
        'question_text': 'Tenho prazos impossíveis de cumprir?',
        'actions': [
            'Revisar prazos com base em capacidade real de execução.',
            'Implantar validação prévia de prazos com a equipe.',
            'Monitorar indicadores de retrabalho por prazo inadequado.',
        ],
    },
    {
        'step': 2,
        'question_number': 3,
        'question_text': 'Preciso trabalhar com muita intensidade?',
        'actions': [
            'Ajustar metas considerando análise de carga de trabalho.',
            'Implementar rodízio de tarefas de alta exigência.',
            'Monitorar riscos psicossociais via avaliação periódica.',
        ],
    },
    {
        'step': 2,
        'question_number': 4,
        'question_text': 'Deixo tarefas de lado por excesso de demandas?',
        'actions': [
            'Definir limite máximo de demandas simultâneas.',
            'Readequar dimensionamento de pessoal.',
            'Implantar matriz de priorização formal.',
        ],
    },
    {
        'step': 2,
        'question_number': 5,
        'question_text': 'Não tenho pausas suficientes?',
        'actions': [
            'Instituir pausas obrigatórias registradas.',
            'Ajustar metas para garantir intervalos adequados.',
            'Fiscalizar cumprimento das pausas pela liderança.',
        ],
    },
    {
        'step': 2,
        'question_number': 6,
        'question_text': 'Sofro pressão para trabalhar longas horas?',
        'actions': [
            'Monitorar jornada via controle formal de horas.',
            'Proibir metas condicionadas a extrapolação de jornada.',
            'Implementar política de desconexão fora do expediente.',
        ],
    },
    {
        'step': 2,
        'question_number': 7,
        'question_text': 'Preciso trabalhar muito rápido?',
        'actions': [
            'Revisar metas de produtividade excessivas.',
            'Ajustar processos para reduzir urgências constantes.',
            'Implantar indicadores de qualidade além da velocidade.',
        ],
    },
    {
        'step': 2,
        'question_number': 8,
        'question_text': 'Pausas temporárias impossíveis de cumprir?',
        'actions': [
            'Formalizar escala com substituição programada.',
            'Ajustar cronograma para permitir intervalos.',
            'Monitorar cumprimento das pausas no PGR.',
        ],
    },
    {
        'step': 3,
        'question_number': 9,
        'question_text': 'Posso decidir quando fazer pausa?',
        'actions': [
            'Formalizar autonomia para pausas dentro da jornada.',
            'Orientar líderes a respeitar intervalos legais.',
            'Monitorar cumprimento via auditoria interna.',
        ],
    },
    {
        'step': 3,
        'question_number': 10,
        'question_text': 'Tenho voz sobre a velocidade do trabalho?',
        'actions': [
            'Criar reuniões de alinhamento de ritmo operacional.',
            'Permitir revisão formal de metas excessivas.',
            'Implantar canal de sugestão confidencial.',
        ],
    },
    {
        'step': 3,
        'question_number': 11,
        'question_text': 'Tenho autonomia sobre como faço meu trabalho?',
        'actions': [
            'Estimular participação na definição de processos.',
            'Reduzir microgerenciamento excessivo.',
            'Formalizar autonomia técnica no descritivo de cargo.',
        ],
    },
    {
        'step': 3,
        'question_number': 12,
        'question_text': 'Tenho autonomia sobre o que faço?',
        'actions': [
            'Definir responsabilidades claras por função.',
            'Delegar decisões compatíveis com o cargo.',
            'Registrar autonomia no manual interno.',
        ],
    },
    {
        'step': 3,
        'question_number': 13,
        'question_text': 'Tenho influência sobre como realizo o trabalho?',
        'actions': [
            'Criar grupos de melhoria contínua.',
            'Implementar sistema de sugestões formal.',
            'Realizar reuniões periódicas de escuta ativa.',
        ],
    },
    {
        'step': 3,
        'question_number': 14,
        'question_text': 'Horário pode ser flexível?',
        'actions': [
            'Avaliar banco de horas ou jornada flexível.',
            'Permitir ajustes mediante acordo formal.',
            'Atualizar política de jornada conforme análise ergonômica.',
        ],
    },
    {
        'step': 4,
        'question_number': 15,
        'question_text': 'Recebo informações e suporte adequados?',
        'actions': [
            'Implantar reuniões semanais de alinhamento técnico.',
            'Criar manual de processos atualizado.',
            'Estabelecer canal direto para dúvidas operacionais.',
        ],
    },
    {
        'step': 4,
        'question_number': 16,
        'question_text': 'Posso contar com meu supervisor?',
        'actions': [
            'Capacitar líderes em gestão de apoio.',
            'Implantar política de acompanhamento individual.',
            'Monitorar clima organizacional periodicamente.',
        ],
    },
    {
        'step': 4,
        'question_number': 17,
        'question_text': 'Posso conversar com supervisor sobre incômodos?',
        'actions': [
            'Criar rotina de feedback individual.',
            'Implantar canal confidencial de comunicação.',
            'Treinar liderança em escuta ativa.',
        ],
    },
    {
        'step': 4,
        'question_number': 18,
        'question_text': 'Recebo apoio em trabalhos emocionalmente exigentes?',
        'actions': [
            'Oferecer apoio psicossocial quando necessário.',
            'Treinar gestores em identificação de sobrecarga emocional.',
            'Ajustar tarefas de alta carga emocional.',
        ],
    },
    {
        'step': 4,
        'question_number': 19,
        'question_text': 'Supervisor me incentiva?',
        'actions': [
            'Implementar política formal de reconhecimento.',
            'Capacitar líderes em feedback positivo.',
            'Monitorar indicadores de engajamento.',
        ],
    },
    {
        'step': 5,
        'question_number': 20,
        'question_text': 'Colegas podem me ajudar?',
        'actions': [
            'Definir metas coletivas de equipe.',
            'Promover integração intersetorial.',
            'Formalizar cultura de cooperação.',
        ],
    },
    {
        'step': 5,
        'question_number': 21,
        'question_text': 'Recebo apoio dos colegas?',
        'actions': [
            'Criar rotina de reuniões colaborativas.',
            'Implantar mediação de conflitos.',
            'Incentivar trabalho em duplas ou times.',
        ],
    },
    {
        'step': 5,
        'question_number': 22,
        'question_text': 'Recebo respeito dos colegas?',
        'actions': [
            'Implementar código de conduta formal.',
            'Realizar treinamentos sobre respeito no trabalho.',
            'Aplicar medidas disciplinares em caso de desrespeito.',
        ],
    },
    {
        'step': 5,
        'question_number': 23,
        'question_text': 'Colegas ouvem meus problemas?',
        'actions': [
            'Estimular cultura de escuta ativa.',
            'Criar espaços formais de diálogo.',
            'Realizar dinâmicas de fortalecimento de equipe.',
        ],
    },
    {
        'step': 6,
        'question_number': 24,
        'question_text': 'Sou perseguido no trabalho?',
        'actions': [
            'Implantar política de prevenção ao assédio.',
            'Criar canal confidencial de denúncia.',
            'Garantir apuração imparcial documentada.',
        ],
    },
    {
        'step': 6,
        'question_number': 25,
        'question_text': 'Há atritos entre colegas?',
        'actions': [
            'Realizar mediação estruturada de conflitos.',
            'Promover treinamento em comunicação não violenta.',
            'Monitorar clima organizacional trimestralmente.',
        ],
    },
    {
        'step': 6,
        'question_number': 26,
        'question_text': 'Falam comigo de forma dura?',
        'actions': [
            'Implantar política de respeito interpessoal.',
            'Treinar equipe em postura profissional.',
            'Aplicar advertência em casos recorrentes.',
        ],
    },
    {
        'step': 6,
        'question_number': 27,
        'question_text': 'Relacionamentos estão desgastados?',
        'actions': [
            'Realizar pesquisa de clima organizacional.',
            'Promover ações de integração periódicas.',
            'Implantar plano de melhoria de ambiente.',
        ],
    },
    {
        'step': 7,
        'question_number': 28,
        'question_text': 'Entendo o que é esperado de mim?',
        'actions': [
            'Formalizar metas individuais documentadas.',
            'Realizar reunião de alinhamento trimestral.',
            'Atualizar descritivo de cargo.',
        ],
    },
    {
        'step': 7,
        'question_number': 29,
        'question_text': 'Sei como realizar meu trabalho?',
        'actions': [
            'Oferecer treinamento técnico contínuo.',
            'Disponibilizar procedimentos operacionais.',
            'Implementar acompanhamento inicial supervisionado.',
        ],
    },
    {
        'step': 7,
        'question_number': 30,
        'question_text': 'Sei minhas funções e responsabilidades?',
        'actions': [
            'Formalizar descrição de cargo detalhada.',
            'Divulgar organograma atualizado.',
            'Validar entendimento em reunião individual.',
        ],
    },
    {
        'step': 7,
        'question_number': 31,
        'question_text': 'Compreendo metas do departamento?',
        'actions': [
            'Apresentar metas estratégicas trimestralmente.',
            'Divulgar indicadores departamentais.',
            'Realizar reuniões de alinhamento.',
        ],
    },
    {
        'step': 7,
        'question_number': 32,
        'question_text': 'Compreendo contribuição do meu trabalho?',
        'actions': [
            'Demonstrar vínculo entre tarefa e resultado organizacional.',
            'Apresentar metas globais da empresa.',
            'Integrar indicadores individuais ao estratégico.',
        ],
    },
    {
        'step': 8,
        'question_number': 33,
        'question_text': 'Posso questionar gestores sobre mudanças?',
        'actions': [
            'Criar fórum formal para esclarecimentos.',
            'Implantar canal aberto de comunicação.',
            'Garantir retorno formal às dúvidas apresentadas.',
        ],
    },
    {
        'step': 8,
        'question_number': 34,
        'question_text': 'Funcionários são consultados sobre mudanças?',
        'actions': [
            'Realizar consulta prévia antes de mudanças relevantes.',
            'Aplicar pesquisa interna de opinião.',
            'Registrar participação no processo decisório.',
        ],
    },
    {
        'step': 8,
        'question_number': 35,
        'question_text': 'Mudanças são claramente explicadas?',
        'actions': [
            'Divulgar plano de transição documentado.',
            'Realizar reunião explicativa antes da implementação.',
            'Disponibilizar comunicado formal detalhado.',
        ],
    },
]


def seed_standard_action_plans(apps, schema_editor):
    StandardActionPlan = apps.get_model('core', 'StandardActionPlan')
    Company = apps.get_model('tenancy', 'Company')
    trigger_score = Decimal('4.30')
    for company in Company.objects.all():
        for item in ACTION_PLAN_DATA:
            StandardActionPlan.objects.update_or_create(
                company=company,
                question_number=item['question_number'],
                defaults={
                    'step': item['step'],
                    'question_text': item['question_text'],
                    'actions': item['actions'],
                    'trigger_score_lt': trigger_score,
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_standard_action_plan'),
        ('tenancy', '0014_alter_company_logo'),
    ]

    operations = [
        migrations.RunPython(seed_standard_action_plans),
    ]
