# Generated by Django 6.0.1 on 2026-02-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_standard_action_plan_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignresponse',
            name='job_function',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='campaign_responses',
                to='core.jobfunction',
            ),
        ),
    ]
