# Generated by Django 6.0.1 on 2026-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_standardactionplan_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome')),
                ('empresa', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('cargo', models.CharField(blank=True, choices=[('rh', 'RH / Recursos Humanos'), ('sesmt', 'SESMT / SST'), ('direcao', 'Direção / C-Level'), ('juridico', 'Jurídico / Compliance'), ('ti', 'TI / Tecnologia'), ('outro', 'Outro')], default='', max_length=20, verbose_name='Cargo')),
                ('num_funcionarios', models.CharField(blank=True, choices=[('ate50', 'Até 50'), ('51_200', '51 – 200'), ('201_500', '201 – 500'), ('501_1000', '501 – 1.000'), ('1000+', 'Acima de 1.000')], default='', max_length=20, verbose_name='Nº de colaboradores')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Interesse (landing page)',
                'verbose_name_plural': 'Interesses (landing page)',
                'db_table': 'landing_interesse',
                'ordering': ['-criado_em'],
            },
        ),
    ]
